project_id = "optistuvyeiojlgmkdks"

[functions.daily-report]
enabled = true
verify_jwt = false
import_map = "./functions/daily-report/deno.json"
entrypoint = "./functions/daily-report/index.ts"

[functions.whatsapp-webhook]
enabled = true
verify_jwt = false
entrypoint = "./functions/whatsapp-webhook/index.ts"

[functions.whatsapp-worker]
enabled = true
verify_jwt = false
entrypoint = "./functions/whatsapp-worker/index.ts"

[functions.process-authorization]
enabled = true
verify_jwt = false
entrypoint = "./functions/process-authorization/index.ts"

[functions.submit-authorization]
enabled = true
verify_jwt = false
entrypoint = "./functions/submit-authorization/index.ts"

[functions.send-whatsapp]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-whatsapp/index.ts"

[functions.send-submission-notification]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-submission-notification/index.ts"

[functions.send-referral-notification]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-referral-notification/index.ts"
